### ISSUE TITLE
Sample Pipeline for RefArch Applications

### ISSUE THREAD

**Issue by ejcsid** [it-at-m/sps#24]
Repos:
- https://github.com/it-at-m/sps-frontend - Create Frontend Image sps-frontend
- https://github.com/it-at-m/sps-backend - Create Backend Image sps-backend
- https://github.com/it-at-m/helm-charts - Use refarch-apigateway helm chart,, sps-frontend- & sps-backend-Backend Image
- set up it@m-internal pipeline to deploy helm chart to it@m infrastructure
- create documentation
```[tasklist]
### Tasks
- [x] Create Pipeline to create sps-frontend image
- [x] Create Pipeline to create spsp-backend image
- [x] Create Helm Chart for sps-application (using refarch-apigateway helm-chart)
- [ ] set up it@m internal pipeline to deploy sps to it@m infrastructure
- [ ] external documentation for external pipelines & helm chart (in .github, refarch verlinkt darauf)
- [ ] internal documetation for internal pipeline
```

**Comment by hupling** [comment]
Create Pipeline to create sps-backend image

Hier wird es Probleme geben. Ich habe schon die Images für Frontend und Backend. Es hat sich leider wieder die Config vom refarch-template geändert, sodass die Variablen anders im Helm Chart konfiguriert werden müssen

**Comment by ejcsid** [comment]
We should ask for tags / releases of refarch-components that we can use to set up the pipelines.

**Comment by ejcsid** [comment]
@hupling copy pipline files from refarch project to this repo and test pipelines. If running, ticket can be closed

**Comment by hupling** [comment]
@ejcsid I think the docs should be central together with the refarch docs.

here everything is also together https://git.muenchen.de/ccse/ospo/-/wikis/home

**Comment by ejcsid** [comment]
> here everything is also together https://git.muenchen.de/ccse/ospo/-/wikis/home

This is an internal repo. Docs for refarch and Actions (.github) should be Open Source. Let's have a look if it's possible to generate with vitepress a common website. Alternatively we can use one repo to keep refarch and actions docs (refarch, .github or a separate doc-repo). Otherwise we have to use links.
